### ISSUE TITLE
Build `kompile` performance tracker

### ISSUE THREAD

**Issue by Baltoli** [runtimeverification/k#3517]
LLVM has a [webpage](https://llvm-compile-time-tracker.com/) where the change in compilation performance over time is tracked against a set of benchmarks. Currently, we don't have a good idea of how the `kompile` pipeline performs, although we are [doing some work](https://github.com/runtimeverification/k/issues/3491) on improving our insight into this.

It would be useful to implement our own version of this tool so that significant performance regressions (or, improvements!) can be identified systematically.

A rough idea of what we'd need to do to implement this is:
* [x] Identify a set of benchmark definitions that can be fed into `kompile` with minimal setup or tinkering (C, EVM, IMP, Foundry proofs...).
* [x] Work out a metric to measure (mean wall clock time over _N_ repetitions as a simple first cut).
* [x] Write scripts to do the benchmarking and write the results into a file somewhere (for now, can probably just be an append-only log in a git repo for simplicity)
* [x] Write scripts to generate some static HTML from those results and commit them to a Github pages branch.
* [ ] Run the above on a `workflow_dispatch` from K release jobs (or commits to master, etc.)

**Comment by Robertorosmaninho** [comment]
The current status for this task is as follows:
 - We decided to use [IMP](https://github.com/runtimeverification/imp-semantics), [Elrond](https://github.com/runtimeverification/elrond-semantics), [KEVM](https://github.com/runtimeverification/evm-semantics), and K's [IMP lesson 5](https://github.com/runtimeverification/k/tree/master/k-distribution/pl-tutorial/1_k/2_imp/lesson_5) and [LAMBDA lesson 9](https://github.com/runtimeverification/k/tree/master/k-distribution/pl-tutorial/1_k/1_lambda/lesson_9).
 - For now, we will work within two metrics: Elapsed time to build the semantics (for LLVM Backend) and its maximum [RSS](https://en.wikipedia.org/wiki/Resident_set_size), both got from Unix `time`. The experiments will initially run ten times, and we'll take the mean of each metric.
 - We'll use the framework [Bencher](bencher.dev) to log, compare and display the result of the benchmarks.

**Comment by ehildenb** [comment]
Instead of cloning the remote semantics repositories (which is network intensive), we can instead do `kompile -E ...` on these definitions, and save the resulting k files directly in the K repo.

The definitions may need to be tweaked to remove the things that caused them to break when removed from their own build systems.

**Comment by ehildenb** [comment]
Also, we could consider using [wasm-semantics](https://github.com/runtimeverification/wasm-semantics), another medium/large one that had performance problems in the past is [avm-semantics](https://github.com/runtimeverification/avm-semantics).

**Comment by ehildenb** [comment]
These tests should go in their own folder, not in `regression-new`. Perhaps a new `profiling` directory? Or a new `integration` directory? They should be a separate stage on CI.

Will we block merging on CI if they fail? Maybe not, it can be non-required. We can set a CI timeout on it, and ewe also have the `performance` runner which this test can run on for consistent experience.

**Comment by ehildenb** [comment]
To speed things up, we could also save the ubuntu jammy package built here (https://github.com/runtimeverification/k/blob/645ffc4d6e3c34de3d85574a93604c9507af222e/.github/workflows/test-pr.yml#L111C1-L130C29), and use that for running the profiling job.
